---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dt_api_host }}"
        dt_api_token: "{{ dt_api_token }}"
        delay: 10

  rules:

    # - name: Problem payload Dynatrace for CPU issue
    #   condition: event.title is match("CPU saturation")
    #   action:
    #     run_job_template:
    #       name: "Remediate CPU saturation issue"
    #       organization: "Default"

    - name: Catch all remaining
      condition: event.meta is defined
      action:
        debug:
