---
- name: Respond to webhook POST
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: R1 - Debug all
      condition: event.meta is defined
      action:
        debug:
